### ISSUE TITLE
9.3 Unable to resolve service for type 'Microsoft.Extensions.Options.IOptions'

### ISSUE THREAD

**Issue by rpatwaricdx** [adeneys/cortex-processing-demo#1]
I am trying to run this demo on Sitecore 9.3. Made the appropriate changes following the instructions and get this error. (Log attached)

Unable to resolve service for type 'Microsoft.Extensions.Options.IOptions`1[ProcessingEngineDemo.Common.SpotifyMusicRecommenderOptions]
[xconnect-log-RPATWARI-PK-Processing-20200426.txt](https://github.com/adeneys/cortex-processing-demo/files/4535369/xconnect-log-RPATWARI-PK-Processing-20200426.txt)

**Comment by adeneys** [comment]
There's a bit of a mismatch between the configuration of the console app and the Cortex processing engine which I started to try and fix, but got distracted. Update the constructor of the `SpotifyMusicRecommender` to accept an `IConfiguration` and do the options binding in there. Here's an example:

        public SpotifyMusicRecommender(IConfiguration configuration)
        {
            if (configuration == null)
                throw new ArgumentNullException(nameof(configuration));

            var options = new SpotifyMusicRecommenderOptions();
            var configSection = configuration.GetSection("spotify");
            configSection.Bind(options);

            _options = options;
        }

This however will break the console app. But if you don't want to test the spotify recommender from the console, that's probably fine.

**Comment by rpatwaricdx** [comment]
Thanks! Will give it a try.
